---

# BEGIN
spring:
    output:
        ansi:
            enabled: always
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
# END
